version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      # - restore_npm
      - run:
          name: Install npm install
          command: npm install
      - run:
          name: Install lint
          command: |
            npm install -D eslint &&
            npm install -D eslint-plugin-react
            npm install -D eslint-config-airbnb
      - run:
          name: Execute lint
          command: node_modules/.bin/eslint .
      # - save_npm
  # lint:
  #   executor:
  #     name: default
  #   steps:
  #     - checkout
  #     # - restore_npm
  #     - run:
  #         name: Run lint
  #         command: npm run lint

workflows:
  linting:
    jobs:
      - setup
      # - lint:
      #     requires:
      #       - setup